# Generated by Django 6.0.7 on 2026-08-02 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(help_text='Dirección literal, ej: Avenida 18 758', max_length=200)),
                ('es_propia', models.BooleanField(default=False, help_text='Marcar solo para Farmacia Astegiano y Farmacia Komorovski')),
            ],
            options={
                'verbose_name_plural': 'Farmacias',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='turnos.farmacia')),
            ],
            options={
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha'],
            },
        ),
    ]
