# Generated by Django 6.0.7 on 2026-08-02 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0003_remove_sucursal_esta_de_turno'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacia',
            name='es_propia',
        ),
        migrations.AddField(
            model_name='farmacia',
            name='sucursal',
            field=models.OneToOneField(blank=True, help_text='Vincular solo si es una de nuestras sucursales (Astegiano / Komorovski)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmacia_turno', to='sucursales.sucursal'),
        ),
    ]
