# Generated by Django 6.1 on 2026-08-15 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero en el listado.')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('sku', models.CharField(help_text='Código interno de la web (único).', max_length=50, unique=True)),
                ('codigo_barras', models.CharField(blank=True, help_text='Para cruzar con Praxys cuando haya sync.', max_length=50)),
                ('codigo_praxys', models.CharField(blank=True, help_text='Id del producto en Observer Praxys, si se conoce.', max_length=50)),
                ('tipo', models.CharField(choices=[('inmediato', 'Venta inmediata (con stock web)'), ('encargue', 'A encargue (confirma staff, después se cobra)')], default='inmediato', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de venta en la web.', max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='catalogo/')),
                ('requiere_receta', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True, help_text='Desactivar oculta el producto en la tienda sin borrarlo.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
    ]
