# Generated by Django 6.1 on 2026-09-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, help_text='Clase de Bootstrap Icons, ej: "bi bi-sun". Ver icons.getbootstrap.com', max_length=60),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Mostrar en la portada, sección "Destacados".'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio antes del descuento. Dejar vacío si no está en oferta.', max_digits=10, null=True),
        ),
    ]
