# Generated by Django 6.1 on 2026-09-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_categoria_icono_producto_destacado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='origen_perfume',
            field=models.CharField(blank=True, choices=[('nacional', 'Nacional'), ('importado', 'Importado'), ('arabe', 'Árabe')], help_text='Solo para la categoría Perfumes: nacional, importado o árabe.', max_length=12),
        ),
    ]
