# Generated by Django 6.1 on 2026-08-26 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('modo', models.CharField(blank=True, choices=[('inmediato', 'Venta inmediata'), ('encargue', 'A encargue')], max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'carrito',
                'verbose_name_plural': 'carritos',
            },
        ),
        migrations.CreateModel(
            name='LineaCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='carrito.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_carrito', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'línea de carrito',
                'verbose_name_plural': 'líneas de carrito',
                'constraints': [models.UniqueConstraint(fields=('carrito', 'producto'), name='unica_linea_producto_por_carrito')],
            },
        ),
    ]
