"""
Django settings for FarmaciaAstegiano project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from decimal import Decimal

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# le decimos a dotenv que cargue las variables del archivo .env:
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Valores que a veces quedan copiados del .env.example o de tutoriales.
# Si alguien arranca con uno de estos, Django aborta: no hay clave secreta real.
_SECRET_KEY_PLACEHOLDERS = frozenset(
    {
        'cambia-esto-por-una-clave-secreta',
        'changeme',
        'change-me',
        'change_me',
        'secret',
        'secret_key',
        'your-secret-key',
        'your-secret-key-here',
        'insecure',
        'placeholder',
        '<clave-larga-aleatoria>',
    }
)


def _resolve_secret_key(raw: str | None) -> str:
    """Fail-fast si SECRET_KEY falta, está vacía o es un placeholder obvio."""
    key = (raw or '').strip()
    if not key or key.lower() in _SECRET_KEY_PLACEHOLDERS:
        raise ImproperlyConfigured(
            'SECRET_KEY falta, está vacía o es un placeholder. '
            'Generá una clave propia con: '
            'python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())" '
            'y definila en backend/.env (ver backend/.env.example).'
        )
    return key


SECRET_KEY = _resolve_secret_key(os.environ.get('SECRET_KEY'))

#Convertimos el string true o false del env a un booleano real de python:
DEBUG = os.environ.get('DEBUG') == 'True'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/





# En desarrollo permitimos localhost; en producción definí ALLOWED_HOSTS en el .env
# separado por comas, ej: ALLOWED_HOSTS=midominio.com,www.midominio.com
if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']
    # Para ngrok/cloudflared en pruebas de webhook MP:
    ALLOWED_HOSTS += [
        host.strip()
        for host in os.environ.get('EXTRA_ALLOWED_HOSTS', '').split(',')
        if host.strip()
    ]
else:
    ALLOWED_HOSTS = [
        host.strip()
        for host in os.environ.get('ALLOWED_HOSTS', '').split(',')
        if host.strip()
    ]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'servicios',
    'sucursales',
    'turnos',
    'aboutUs',
    'catalogo',
    'inventario',
    'carrito',
    'pedidos',
    'pagos',
    'cuentas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FarmaciaAstegiano.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS se busca ANTES que los templates de cada app: acá van los que
        # pisan a terceros (ej. registration/login.html de django.contrib.auth,
        # que si no lo pisamos usaría el del admin).
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.banner_turno',
                'core.context_processors.datos_footer',
                'core.context_processors.navegacion_tienda',
                'core.context_processors.carrito_resumen',
            ],
        },
    },
]

WSGI_APPLICATION = 'FarmaciaAstegiano.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --- Cuentas de clientes ---
# LOGIN_URL: adónde manda @login_required a los anónimos (con ?next=...).
# Los otros dos son los destinos por defecto tras loguearse / desloguearse.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'catalogo_lista'
LOGOUT_REDIRECT_URL = 'inicio'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Cordoba'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Carpeta del proyecto con CSS/JS/imágenes propias (además de los static de cada app).
# En desarrollo Django los sirve solo; en producción se copian a STATIC_ROOT con collectstatic.
STATICFILES_DIRS = [BASE_DIR / 'static']

# URL que vera el navegador: 
MEDIA_URL = '/media/'

# Carpeta fisica donde se guardan las imagenes en el pc
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- Tienda: pagos e inventario ---
MERCADOPAGO_ACCESS_TOKEN = os.environ.get('MERCADOPAGO_ACCESS_TOKEN', '')
MERCADOPAGO_PUBLIC_KEY = os.environ.get('MERCADOPAGO_PUBLIC_KEY', '')
MERCADOPAGO_WEBHOOK_SECRET = os.environ.get('MERCADOPAGO_WEBHOOK_SECRET', '')

# URL pública del sitio (ngrok o dominio). Vacío = usar host del request (localhost).
SITE_URL = os.environ.get('SITE_URL', '').rstrip('/')

RESERVA_STOCK_TTL_MINUTOS = int(os.environ.get('RESERVA_STOCK_TTL_MINUTOS', '60'))

TRANSFERENCIA_ALIAS = os.environ.get('TRANSFERENCIA_ALIAS', '')
TRANSFERENCIA_CBU = os.environ.get('TRANSFERENCIA_CBU', '')

# Costo de envío (Fase 4): monto fijo; gratis si subtotal >= ENVIO_GRATIS_DESDE
ENVIO_MONTO_FIJO = Decimal(os.environ.get('ENVIO_MONTO_FIJO', '1500'))
ENVIO_GRATIS_DESDE = Decimal(os.environ.get('ENVIO_GRATIS_DESDE', '0'))

# WhatsApp de contacto tienda (sin + ni espacios, ej. 5493471543210)
WHATSAPP_TIENDA = os.environ.get('WHATSAPP_TIENDA', '')

# Email (SMTP) — notificaciones de estado de pedido
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'tienda@farmacia.local')