# Generated by Django 6.0.7 on 2026-07-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(help_text='Ingrese una descripción breve de la empresa')),
                ('imagen', models.ImageField(help_text='Suba una imagen de la empresa', upload_to='aboutUs/')),
            ],
        ),
    ]
