# Generated by Django 6.1 on 2026-08-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrenosotros',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Suba una imagen de la empresa', null=True, upload_to='aboutUs/'),
        ),
    ]
