# Generated by Django 6.1 on 2026-09-16 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0002_alter_sobrenosotros_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sobrenosotros',
            options={'verbose_name': 'sección Quiénes somos', 'verbose_name_plural': 'sección Quiénes somos'},
        ),
    ]
