# Generated by Django 6.1 on 2026-09-16 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0003_remove_sucursal_esta_de_turno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('empleada', 'Empleada / empleado'), ('duenio', 'Dueño (super cuenta)')], default='empleada', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('mensaje', models.CharField(blank=True, help_text='Texto que dejó la persona al solicitar acceso.', max_length=300)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_aprobados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(blank=True, help_text='Sucursal donde trabaja habitualmente (informativo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to='sucursales.sucursal')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuenta de personal',
                'verbose_name_plural': 'cuentas de personal',
                'ordering': ['-created_at'],
            },
        ),
    ]
