# Generated by Django 6.1 on 2026-08-16 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, help_text='Unidades publicables ahora.')),
                ('tope_web', models.PositiveIntegerField(blank=True, help_text='Máximo a publicar. Vacío = sin tope. Se usa al importar.', null=True)),
                ('margen_seguridad', models.PositiveIntegerField(default=0, help_text='Al importar: stock_web = stock_praxys − este número.')),
                ('origen', models.CharField(choices=[('manual', 'Carga manual (admin)'), ('csv', 'Importación CSV'), ('api', 'API Praxys')], default='manual', max_length=10)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'stock web',
                'verbose_name_plural': 'stocks web',
            },
        ),
    ]
