# Generated by Django 6.1 on 2026-08-27 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('inventario', '0001_initial'),
        ('pedidos', '0003_pedido_confirmado_en_pedido_reservado_hasta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('consolidada', 'Consolidada (vendida)'), ('liberada', 'Liberada (cancelación)'), ('expirada', 'Expirada (timeout)')], default='activa', max_length=15)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'reserva de stock',
                'verbose_name_plural': 'reservas de stock',
                'indexes': [models.Index(fields=['estado', 'expires_at'], name='inventario__estado_54a5c5_idx')],
            },
        ),
    ]
