# Generated by Django 6.1 on 2026-08-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_reservastock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(choices=[('csv', 'CSV'), ('api', 'API')], max_length=10)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='importaciones/')),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('detalle', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'importación de stock',
                'verbose_name_plural': 'importaciones de stock',
                'ordering': ['-iniciada_en'],
            },
        ),
    ]
