# Generated by Django 6.1 on 2026-08-27 18:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('sucursales', '0003_remove_sucursal_esta_de_turno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FranjaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'franja de envío',
                'verbose_name_plural': 'franjas de envío',
                'ordering': ['orden', 'hora_desde'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('pendiente_transferencia', 'Pendiente transferencia'), ('pendiente_encargue', 'Pendiente confirmación encargue'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('entregado', 'Entregado')], max_length=30)),
                ('modo', models.CharField(choices=[('inmediato', 'Venta inmediata'), ('encargue', 'A encargue')], max_length=20)),
                ('modalidad_entrega', models.CharField(choices=[('retiro_sucursal', 'Retiro en sucursal'), ('a_coordinar', 'A coordinar'), ('envio', 'Envío a domicilio')], max_length=20)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('direccion_envio', models.TextField(blank=True)),
                ('medio_pago', models.CharField(blank=True, choices=[('mercadopago', 'Mercado Pago'), ('credito', 'Tarjeta de crédito'), ('debito', 'Tarjeta de débito'), ('transferencia', 'Transferencia bancaria')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franja_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos.franjaenvio')),
                ('sucursal_retiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_retiro', to='sucursales.sucursal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_snapshot', models.CharField(max_length=150)),
                ('sku_snapshot', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_pedido', to='catalogo.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'línea de pedido',
                'verbose_name_plural': 'líneas de pedido',
            },
        ),
    ]
