# Generated by Django 6.1 on 2026-08-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_franjas_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='confirmado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='reservado_hasta',
            field=models.DateTimeField(blank=True, help_text='Hasta cuándo se reserva el stock (pedidos inmediatos).', null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('pendiente_transferencia', 'Pendiente transferencia'), ('pendiente_encargue', 'Pendiente confirmación encargue'), ('pendiente_pago_encargue', 'Encargue aprobado — pendiente pago'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('listo_retiro', 'Listo para retiro'), ('despachado', 'Despachado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=30),
        ),
    ]
