# Generated by Django 6.1 on 2026-08-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_confirmado_en_pedido_reservado_hasta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franjaenvio',
            name='cupo_max',
            field=models.PositiveIntegerField(blank=True, help_text='Máximo de pedidos por día en esta franja. Vacío = sin límite.', null=True),
        ),
    ]
