# Generated by Django 6.1 on 2026-08-28 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_franjaenvio_cupo_max'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('pendiente_pago', 'Pendiente de pago'), ('pendiente_transferencia', 'Pendiente transferencia'), ('pendiente_encargue', 'Pendiente confirmación encargue'), ('pendiente_pago_encargue', 'Encargue aprobado — pendiente pago'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('listo_retiro', 'Listo para retiro'), ('despachado', 'Despachado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=30)),
                ('estado_nuevo', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('pendiente_transferencia', 'Pendiente transferencia'), ('pendiente_encargue', 'Pendiente confirmación encargue'), ('pendiente_pago_encargue', 'Encargue aprobado — pendiente pago'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('listo_retiro', 'Listo para retiro'), ('despachado', 'Despachado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=30)),
                ('detalle', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Vacío = acción automática del sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_pedido', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'evento de pedido',
                'verbose_name_plural': 'eventos de pedido',
                'ordering': ['created_at'],
            },
        ),
    ]
