# Generated by Django 6.0.7 on 2026-07-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_fachada', models.ImageField(blank=True, null=True, upload_to='sucursales/')),
                ('direccion', models.CharField(max_length=200)),
                ('link_google_maps', models.URLField(max_length=500)),
                ('telefono_fojo', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_whatsapp', models.CharField(blank=True, help_text='ingrese numero de país +54 9', max_length=15, null=True)),
                ('horarios_atencion', models.TextField(blank=True, null=True)),
                ('esta_de_turno', models.BooleanField(default=False)),
            ],
        ),
    ]
