# Generated by Django 6.0.7 on 2026-07-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='telefono_fojo',
            new_name='telefono_fijo',
        ),
    ]
