# Generated by Django 6.0.7 on 2026-08-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_rename_telefono_fojo_sucursal_telefono_fijo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='esta_de_turno',
        ),
    ]
