# Generated by Django 6.1 on 2026-09-16 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0003_remove_sucursal_esta_de_turno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'sucursal', 'verbose_name_plural': 'sucursales'},
        ),
    ]
