# Generated by Django 6.1 on 2026-09-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('subtitulo', models.CharField(blank=True, max_length=160)),
                ('imagen', models.ImageField(blank=True, help_text='Recomendado 1400×450 px. Si se deja vacío se usa un fondo de marca.', null=True, upload_to='banners/')),
                ('link', models.CharField(blank=True, help_text='Adónde lleva el botón. Puede ser una ruta interna (/tienda/?oferta=1) o una URL.', max_length=300)),
                ('texto_boton', models.CharField(blank=True, default='Ver más', max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero.')),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'banner de portada',
                'verbose_name_plural': 'banners de portada',
                'ordering': ['orden', '-id'],
            },
        ),
    ]
