# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(help_text='Nombre del banco o tarjeta, ej. Banco Nación.', max_length=80)),
                ('beneficio', models.CharField(help_text='Lo que ve el cliente, ej. 20% de descuento / 3 y 6 cuotas sin interés.', max_length=120)),
                ('condiciones', models.TextField(blank=True, help_text='Letra chica: tope, tarjetas, no acumulable, etc.')),
                ('logo', models.ImageField(blank=True, help_text='Logo del banco. Si se deja vacío se usa un ícono genérico.', null=True, upload_to='promos_bancarias/')),
                ('lunes', models.BooleanField(default=False, verbose_name='Lunes')),
                ('martes', models.BooleanField(default=False, verbose_name='Martes')),
                ('miercoles', models.BooleanField(default=False, verbose_name='Miércoles')),
                ('jueves', models.BooleanField(default=False, verbose_name='Jueves')),
                ('viernes', models.BooleanField(default=False, verbose_name='Viernes')),
                ('sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('domingo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero.')),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'promoción bancaria',
                'verbose_name_plural': 'promociones bancarias',
                'ordering': ['orden', 'banco'],
            },
        ),
    ]
