# Generated by Django 6.1 on 2026-08-27 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0003_pedido_confirmado_en_pedido_reservado_hasta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('credito', 'Tarjeta de crédito'), ('debito', 'Tarjeta de débito'), ('transferencia', 'Transferencia bancaria')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_externo', models.CharField(blank=True, max_length=100)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_confirmados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
