# Generated by Django 6.0.7 on 2026-07-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(help_text='Ingrese una descripción breve del servicio')),
                ('icono', models.CharField(help_text='Ingrese el nombre de la clase CSS del icono', max_length=100)),
                ('sucursales_disponibles', models.ManyToManyField(related_name='servicios', to='sucursales.sucursal')),
            ],
        ),
    ]
